INSERT INTO Aeroporto (icao, nome) VALUES ('icao1', 'Aeroporto 1')
INSERT INTO Aeroporto (icao, nome) VALUES ('icao2', 'Aeroporto 2')
INSERT INTO ModeloAeronave (fabricante, nome) values ('fabricante1', 'nomefabricante1')
INSERT INTO ModeloAeronave (fabricante, nome) values ('fabricante2', 'nomefabricante2')
INSERT INTO Piloto (nome, numbreve) VALUES ('nomepiloto1', 'numbreve1')
INSERT INTO Piloto (nome, numbreve) VALUES ('nomepiloto2', 'numbreve2')